import type { Config } from 'dompurify';

export const DOMPURIFY_CONFIG = {
  ALLOWED_TAGS: ['img', 'span', 'p', 's', 'b', 'br', 'renode'],

  ADD_ATTR: ['class', 'className', 'data-shop-item-dir', 'style', 'nodetype'],
  FORBID_TAGS: [
    'a',
    'svg',
    'style',
    'video',
    'audio',
    'input',
    'link',
    'comment',
    'embed',
    'listing',
    'xmp',
    'plaintext',
    'object',
    'iframe',
    'script',
  ],
  FORBID_ATTR: ['action'],
} satisfies Config;
export const DOMPURIFY_CONFIG_WITHOUT_IMG = {
  FORBID_TAGS: ['img'],
};
export const ALLOWED_CLASS_NAMES = [
  'pink-glow',
  'green-glow',
  'yellow-glow',
  'purple-glow',
  'orange-glow',
  'sticker',
  'teal-glow',
  'red-glow',
  'indigo-glow',
  'light-blue-glow',
  'lime-glow',
  'coral-glow',
  'amber-glow',
  'cyan-glow',
  'deep-purple-glow',
  'peach-glow',
  'blue-glow-bold-large',
  'pink-glow-light-small',
  'green-glow-regular-medium',
  'purple-glow-bold-large',
  'yellow-glow-light-small',
  'teal-glow-medium-medium',
  'red-glow-bold-xlarge',
  'indigo-glow-regular-small',
  'orange-glow-light-medium',
  'cyan-glow-bold-large',
  'deep-purple-glow-light-medium',
  'lime-glow-regular-large',
  'coral-glow-bold-small',
  'peach-glow-medium-large',
  'amber-glow-bold-medium',
  'sticker',
  'sticker-single',
  'sticker-emoji',
];
