export const typeToName = {
    title_update: 'Изменение тайтла',
    title_add: 'Новый тайтл',
    publisher_add: 'Новый паблишер',
    title_change_publisher: 'Перехват/передача',
    title_new_season: 'Новый сезон',
    creator_add: 'Новый создатель',
    creator_update: 'Изменение создателя',
    title_additional_add: 'Создание ссылок к тайтлу',
    title_additional_update: 'Изменение ссылок тайтла',
    character_update: 'Изменение персонажа',
    character_add: 'Добавление персонажа',
    card_item_add: 'Добавление карточки',
    card_item_update: 'Изменение карточки',
    title_relation_add: 'Добавление связанных тайтлов',
    title_relation_update: 'Изменение связанных тайтлов',
    shop_image_item_add: 'Добавление предмета кастомизации',
    moment_add: 'Добавление момента',
    moment_update: 'Изменение момента',
    title_add_creators: 'Добавление создателей тайтла',
    title_update_creators: 'Изменение создателей тайтла',
};
