export const typography = {
    fontFamily: "'Open Sans', sans-serif",
    htmlFontSize: 16,
    fontSize: 14,
    fontWeightLight: 300,
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    fontWeightBold: 700,
    h1: {
        fontFamily: "'Open Sans', sans-serif",
        fontWeight: 300,
        fontSize: '6rem',
        lineHeight: 1.167,
    },
    h2: {
        fontFamily: "'Open Sans', sans-serif",
        fontWeight: 300,
        fontSize: '3.75rem',
        lineHeight: 1.2,
    },
    h3: {
        fontFamily: "'Open Sans', sans-serif",
        fontWeight: 400,
        fontSize: '3rem',
        lineHeight: 1.167,
    },
    h4: {
        fontFamily: "'Open Sans', sans-serif",
        fontWeight: 400,
        fontSize: '2.125rem',
        lineHeight: 1.235,
    },
    h5: {
        fontFamily: "'Open Sans', sans-serif",
        fontWeight: 400,
        fontSize: '1.5rem',
        lineHeight: 1.334,
    },
    h6: {
        fontFamily: "'Open Sans', sans-serif",
        fontWeight: 500,
        fontSize: '1.25rem',
        lineHeight: 1.6,
    },
    subtitle1: {
        fontFamily: "'Open Sans', sans-serif",
        fontWeight: 400,
        fontSize: '1rem',
        lineHeight: 1.75,
    },
    subtitle2: {
        fontFamily: "'Open Sans', sans-serif",
        fontWeight: 500,
        fontSize: '0.875rem',
        lineHeight: 1.57,
    },
    body1: {
        fontFamily: "'Open Sans', sans-serif",
        fontWeight: 400,
        fontSize: '1rem',
        lineHeight: 1.5,
    },
    body2: {
        fontFamily: "'Open Sans', sans-serif",
        fontWeight: 400,
        fontSize: '0.875rem',
        lineHeight: 1.43,
    },
    button: {
        fontFamily: "'Open Sans', sans-serif",
        fontWeight: 500,
        fontSize: '0.875rem',
        lineHeight: 1.75,
        textTransform: 'uppercase',
    },
    caption: {
        fontFamily: "'Open Sans', sans-serif",
        fontWeight: 400,
        fontSize: '0.75rem',
        lineHeight: 1.66,
    },
    overline: {
        fontFamily: "'Open Sans', sans-serif",
        fontWeight: 400,
        fontSize: '0.75rem',
        lineHeight: 2.66,
        textTransform: 'uppercase',
    },
    inherit: {
        fontFamily: 'inherit',
        fontWeight: 'inherit',
        fontSize: 'inherit',
        lineHeight: 'inherit',
        letterSpacing: 'inherit',
    },
};
